project:
  type: book
  output-dir: docs
  
execute: 
  freeze: auto


editor: visual
book: 
  title: Stat 102 Notes
  
  chapters:
    - index.qmd
    - Section-1-Philosophy.qmd
    - Section-2-Proportions.qmd
    - Section-3-Means.qmd

  

  downloads: [pdf]    

format: 
  html: default
  pdf:   
    header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}  
    output-file: pdf-book
    fontsize: 12pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm

   
