project:
  type: book
  output-dir: docs


editor: visual
book: 
  title: Stat 102 Notes
  
  chapters:
    - index.qmd
    - Section 1 Introduction.qmd
    - Section 2 Completely Randomized Design.qmd
    - Section 3 Factorial Treatment Design.qmd
    - Section 4 Block Designs.qmd
    - Section 5 Split Plot Designs.qmd

  downloads: [pdf]    

format: 
  html: default
  pdf:   
    header-includes:
        - \usepackage{float}
        - \floatplacement{table}{H}  
    output-file: pdf-book
    fontsize: 11pt
    geometry: 
      - top=20mm
      - left=15mm
      - right=10mm

   
